name:                untyped
version:             0.1.0.0
github:              "jeffhappily/wyah"
license:             BSD3
author:              "Jeff"
maintainer:          "goodboy96@live.com.my"
copyright:           "2020 Jeff"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeffhappily/wyah#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

executables:
  untyped-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskeline
    - mtl
    - untyped

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers
    - mtl
    - parsec
    - pretty
